from utils import pathToFunc, print_warning, get_config
from datatypes import OrderedSet

import os, re



class Eval:
    WARNINGS = {
        "dependency" : [],
        "main"       : []
    }
    LITERAL = True

    def __init__(self, dependencies: OrderedSet):
        self.dependencies = dependencies

        
        if get_config("implementation") == "interpreter":

            self.NULL = """
def null(x): return x(0) if isinstance(x, type(null)) else None
""" 

            self.PROCESS = lambda literal: f"""
def process(string: str) -> any:
    dFlag = get_config("flags", "d")

    try:
        {"print(str(parse(string, dFlag=dFlag)).strip())" if literal
        else """out = evaluate(parse(string, dFlag=dFlag).AST)
        if out is not None: print(out)"""}
    except Exception as e:
        if e.args[0] == 0:
            print(e.args[1])
        else:
            raise e
        

def validate(parsed: Parsed, solution: any) -> str:
    if str(parsed) == solution: return solution
    
    result = evaluate(parsed.AST)
    
    if result == solution: return solution
    raise ValueError(f"value of '{{parsed}}' should be {{solution}}, but received {{result}}")
"""

        else:

            self.NULL = """
def null(x): return " ".join(map(evaluate, x())).strip() if isinstance(x, type(null)) else None
"""

            self.PROCESS = lambda _: f"""
def process(string: str) -> any:
    try:
        with open("{get_config("output")}", "w") as file:
            file.write(evaluate(parse(string, dFlag=get_config("flags", "d")).AST))

    except Exception as e:
        if e.args[0] == 0:
            print(e.args[1])
        else:
            raise e
"""


    def compile(self) -> str:
        text = """'''!!! THIS FILE IS AUTOMATICALLY GENERATED - PLEASE DO NOT MODIFY !!!'''



from datatypes import Rule, Parsed
from utils import get_config
from parser import parse



##### MODULES #####
""" \
        + "".join(File(dependency).compile() for dependency in self.dependencies) \
        + File().compile() \
        + f"""

        
##### EVAL #####


{self.NULL}

def dispatch(expr: list): 
    def expression(i: int = None):
        if i == None: return expr
        try:
            return evaluate(expr[i])
        except IndexError as e:
            print(f"Error in expression {{expr}}: index {{i}}")
            raise e
    return expression


def get_function(AST: Rule):
    return (
        globals().get(f"{{AST.fname}}_{{AST.variant}}")
        or globals().get(AST.fname)
        or null
    )


def evaluate(AST: Rule):
    return (
        get_function(AST)(dispatch(AST.children)) if isinstance(AST, Rule)
        else AST
    )

{self.PROCESS(Eval.LITERAL)}
"""
        
        print_warning("semantics not found", self.WARNINGS)
        
        return text
    


class File:
    def __init__(self, path: str = None):
        main = f"{get_config("paths", "language")}/{get_config("implementation")}"

        if path: 
            self.type = "DEPENDENCY"
            self.path = path
        else:
            self.type = "MAIN"
            self.path = main

        self.file = f"{self.path}/semantics.py"
        if not os.path.exists(self.file):
            self.file = f"{self.path}/{get_config("implementation")}/semantics.py"


    def compile(self) -> str:
        if not os.path.exists(self.file):
            Eval.WARNINGS[self.type.lower()].append(self.path)
            return ""
    
        with open(self.file) as file:
            Eval.LITERAL = False
            text = self.process(file.read())
            return f"""


### {self.type} : {self.path} ###



""" + text
        

    def process(self, text: str) -> str:

        def replace_fname(match: re.Match) -> str:
            return "def " \
                + pathToFunc(self.path if self.type == "DEPENDENCY" else "main") \
                + match.group().split("p_", 1)[1].lower()

        return re.sub(
            pattern=r"def p_.*\(",
            repl=replace_fname,
            string=text
        )
