from datatypes import OrderedSet

import os



class Eval:
    def __init__(self, path: str, dependencies: OrderedSet):
        self.path = path
        self.dependencies = dependencies


    def compile(self) -> str:
        return """'''!!! THIS FILE IS AUTOMATICALLY GENERATED - PLEASE DO NOT MODIFY !!!'''



from datatypes import Rule, Parsed
from parser import parse
""" \
        + "".join(Dependency(dependency).compile() for dependency in self.dependencies) \
        + Main(self.path).compile() \
        + f"""

        
##### EVAL #####



def null(x): return x(0) if isinstance(x, type(null)) else None


def lazy(expr: list): 
    def expression(i):
        try:
            return evaluate(expr[i])
        except IndexError as e:
            print(f"Error in expression {{expr}}: index {{i}}")
            raise e
    return expression


def get_function(AST: Rule):
    return (
        globals().get(f"{{AST.fname}}_{{AST.variant}}")
        or globals().get(AST.fname)
        or null
    )


def evaluate(AST: Rule):
    return (
        get_function(AST)(lazy(AST.children)) if isinstance(AST, Rule)
        else AST
    )


def process(string: str, dFlag: bool) -> any:
    try:
        out = evaluate(parse(string, dFlag=dFlag).AST)
        if out is not None: print(out)
    except Exception as e:
        if (
            len(e.args) > 1
            and e.args[0] in (0, 1)
        ):
            print(e.args[1])
        else:
            raise e
        

def validate(parsed: Parsed, solution: any) -> str:
    if str(parsed) == solution: return solution
    
    result = evaluate(parsed.AST)
    
    if result == solution: return solution
    raise ValueError(f"value of {{parsed}} should be {{solution}}, but received {{result}}")
"""
    


class File:
    def __init__(self, path: str):
        self.path = path
        self.file = path + "/semantics.py"


    def compile(self) -> str:
        if not os.path.exists(self.file):
            print(f"WARNING: semantics not found in dependency {self.path}")
            return ""

    
        with open(self.file) as file:
            text = file.read()
            return f"""


##### {type(self).__name__} : {self.path} #####

            

""" + text



class Main(File): pass



class Dependency(File): pass