from utils import pathToFunc, print_warnings, get_config
from datatypes import OrderedSet

import os, re



class Eval:
    WARNINGS = {
        "dependency" : [],
        "main"       : []
    }
    LITERAL = True


    def __init__(self, dependencies: OrderedSet):
        self.dependencies = dependencies
        self.exception = """
    except Exception as e:
        if e.args[0] in (0, 1):
            print(e.args[1])
        else:
            raise e
"""

      
    def embed_default(self) -> str:

        if (get_config("implementation") == "interpreter"):
            return """
def default(x): return x(0) if isinstance(x, Expr) else None
"""

        else: 
            return """
def default(x): return " ".join(map(evaluate, x)).strip() if isinstance(x, Expr) else None
"""


    def embed_process(self, isLiteral):

        if (get_config("implementation") == "interpreter"):
            return f"""
def process(string: str) -> any:
    try:
        {"print(str(parse(string)).strip())" if isLiteral
        else """out = evaluate(parse(string).AST)
        if out is not None: print(out)"""}
{self.exception}
        
def validate(parsed, solution: any) -> str:
    if str(parsed) == solution: return solution
    
    result = evaluate(parsed.AST)
    
    if result == solution: return solution
    raise ValueError(f"value of '{{parsed}}' should be {{solution}}, but received {{result}}")
""" 
        
        else:
            return f"""
def process(string: str) -> any:
    try:
        with open("{get_config("output")}", "w") as file:
            file.write(evaluate(parse(string).AST))
{self.exception}
"""


    def compile(self) -> str:
        text = """'''!!! THIS FILE IS AUTOMATICALLY GENERATED - PLEASE DO NOT MODIFY !!!'''



from datatypes import Rule
from parser import parse



##### MODULES #####
""" \
        + "".join(File(dependency).compile() for dependency in self.dependencies) \
        + File().compile() \
        + f"""

        
##### EVAL #####



class Expr(list):
    def __call__(self, i):
        return evaluate(self[i])
   
{self.embed_default()}

def get_function(AST: Rule):
    return (
        globals().get(f"{{AST.fname}}_{{AST.variant}}")
        or globals().get(AST.fname)
        or default
    )


def evaluate(AST: Rule):
    return (
        get_function(AST)(Expr(AST.children)) if isinstance(AST, Rule)
        else AST
    )

{self.embed_process(Eval.LITERAL)}
"""
        
        print_warnings("semantics not found", self.WARNINGS)
        
        return text



class File:
    def __init__(self, path: str = None):
        """Resolve and compile syntax files. 
        Search for semantics.py in `path/<implementation>/`;
        if not found, fall back to `path/`."""

        main = get_config("paths", "language")

        if path: 
            self.type = "DEPENDENCY"
            self.path = path
        else:
            self.type = "MAIN"
            self.path = main

        implementation = get_config("implementation")
        self.file = f"{self.path}/{implementation}/semantics.py"
        if not os.path.exists(self.file):
            if self.type == "MAIN": 
                print_warnings(
                    msg=f"{implementation} semantics not found",
                    log=["semantics may not be implementation-specific"]
                )
            self.file = f"{self.path}/semantics.py"


    def compile(self) -> str:
        if not os.path.exists(self.file):
            Eval.WARNINGS[self.type.lower()].append(self.path)
            return ""
    
        with open(self.file) as file:
            Eval.LITERAL = False
            text = self.process(file.read())
            return f"""


### {self.type} : {self.path} ###



""" + text
        

    def process(self, text: str) -> str:

        def replace_fname(match: re.Match) -> str:
            return \
                pathToFunc(self.path if self.type == "DEPENDENCY" else "main") \
                + match.group().split("p_", 1)[1].lower()

        return re.sub(
            pattern=r"p_.*\(",
            repl=replace_fname,
            string=text
        )
