from datatypes import OrderedSet
from utils import preprocess_text

import os
import re



class Grammar:
    TERMINALS = {}
    K = 0
    MAIN = ""
    

    def __init__(self, path: str):
        self.path = self.MAIN = path
        self.modules = {}
        self.dependencies = self.traverse_dependencies(self.path, main=True)


    def traverse_dependencies(self, path: str, main: bool = False) -> OrderedSet:
        """Recursively search for `#require`s from a top-level path, preserving order and building grammar modules during traversal."""

        syntax = f"{path}/syntax.txt"
        dependencies = OrderedSet()

        if os.path.exists(syntax):

            with open(syntax) as file:
                lines = preprocess_text(file)
                
                basic_requirements = [
                    line.removeprefix("#require").strip().replace(".", "/")
                    for line in lines if line.startswith("#require")
                ]

                requirements = OrderedSet()

                while basic_requirements:
                    requirement = basic_requirements.pop(0)
                    if "/" in requirement:
                        requirements.extend(f".lib/{"/".join(requirement.split("/")[:i+1])}" for i in range(requirement.count("/")))

                    requirements.add(".lib/" + requirement)

                lines = filter(lambda x: not x.startswith("#require"), lines)
                self.modules[path] = Module("MAIN" if main else path, lines)

                dependencies.extend(requirements)

                for requirement in requirements:
                    dependencies.extend(self.traverse_dependencies(requirement))

        else: print(f"WARNING: syntax not found in {"MAIN" if main else "dependency"} {path}")

        return dependencies

    
    @staticmethod
    def add_terminal(rule: 'Nonterminal', terminal: str) -> None:
        """Adds a new terminal to the `Grammar`."""
        Grammar.TERMINALS[rule] = terminal


    def __str__(self) -> str:
        return "\n\n".join(module._str() for module in self.modules.values())
    

    def compile(self) -> str:
        text = f"""'''!!! THIS FILE IS AUTOMATICALLY GENERATED - PLEASE DO NOT MODIFY !!!'''

        

from datatypes import Rule
from utils import *



##### ABSTRACT SYNTAX TREE #####


        {"".join(module.compile() for module in self.modules.values())}

##### GRAMMAR #####



MODULES = {self.embed()}

GRAMMAR = {{}}


for module, subgrammar in MODULES.items():
    for rule, alternatives in subgrammar.items():
        if not rule in GRAMMAR: GRAMMAR[rule] = {{}}
        if not module in GRAMMAR[rule]: GRAMMAR[rule][module] = []

        GRAMMAR[rule][module] += alternatives

        
                
##### ADDENDA #####



TERMINALS = {{
    rule : (module, re.compile(alternatives[0][0]))
            for rule, modules in GRAMMAR.items()
        for module, alternatives in modules.items() if (
    1 == len(alternatives) == len(alternatives[0])
    and isinstance(alternatives[0][0], str)
    )
}}

K = {Grammar.K}

TOKENS = {{
    *TERMINALS,
    *GRAMMAR
}}

EXPECTED_TOKENS = {{
    token : [] for token in TOKENS
}}

EXPECTED_PATTERNS = {{
    token : [] for token in TOKENS
}}

EPSILON = "ε"

EPSILA: set = {{EPSILON}}

INDENT_SENSITIVE = False

NEWLINE_SENSITIVE = False

INDENT = "   "



##### HELPER FUNCTIONS #####



def retype(x): 
    return type(x) if isinstance(x, Rule) else x

    
def expected_patterns(x) -> tuple[Rule, int, list]:
    return EXPECTED_PATTERNS.get(retype(x), [])


def nullable(x): return retype(x) in EPSILA


def expects(previous: Rule|str, next: str|None) -> bool:
    '''Check if `previous` expects `next` or `previous` is `None`.'''
    return previous == None or next == " " or retype(next) in EXPECTED_TOKENS.get(retype(previous), [])



##### GRAMMAR POSTPROCESSING / EXPANSION #####



EPSILA = find_nullable_rules(GRAMMAR)
EXPECTED_TOKENS = build_expected_tokens(GRAMMAR, EPSILA)
EXPECTED_PATTERNS = build_expected_patterns(GRAMMAR)
"""
        
        return text
    
    
    def embed(self) -> str:
        return "{\n\n" + ",\n\n".join(module.embed() for module in self.modules.values()) + "\n\n}"



class Module:
    def __init__(self, name: str, lines: list, sep: str = "::="):
        self.name = "MAIN" if name == Grammar.MAIN else name.removeprefix(".lib/").upper().replace("/", "_")
        self.lines = lines
        self.rules = OrderedSet()

        self.indent = 0

        for line in lines:
            self.rules.add(Production(self, *line.split(sep)))
            self.indent = max(self.indent, line.index(sep)-len(sep))


    def _str(self) -> str:
        return f"{self.name}\n" + "\n".join(production._str(self.indent) for production in self.rules)


    def compile(self) -> str:
        text = f"""
### MODULE : {self.name} ###

{"".join(production.compile() for production in self.rules)}
"""
        
        return text


    def embed(self) -> str:
        return f"'{self.name}' : {{\n" + (
            ",\n".join("   " + production.embed(self.indent) for production in self.rules) if self.rules 
            else "#  No rules found"
        ) + "\n   }"
    


class Production:
    sep = re.compile(r"[^\\]\|")

    
    def __init__(self, module: Module, rule: str, alternatives: str):
        self.module = module

        alternatives = self.sep.split(alternatives)
        variants = len(alternatives)
        
        self.rule, self.alternatives = Nonterminal(rule.strip()), [Pattern(module, rule, pattern, variants) for pattern in alternatives]


    def _str(self, indent: int) -> str:
        return f"{self.rule} {" " * (indent-len(self.rule))} ::= {f"\n{" " * (indent + 5)} | ".join(pattern._str() for pattern in self.alternatives)}"


    def compile(self) -> str:
        text = f"""
class {self.rule.name}(Rule):
   r'''```
{self.rule} ::= {f"\n{" " * (len(self.rule) + 5)}| ".join(pattern.compile() for pattern in self.alternatives)}
    ```'''
"""
        
        return text


    def embed(self, indent: int) -> str:
        return f"{self.rule.name} {" " * (indent-len(self.rule))} : [{f", ".join(pattern.embed() for pattern in self.alternatives)}]"



class Pattern:
    regex = re.compile(r"\<[A-Z0-9_]+\>")


    def __init__(self, module: Module, rule: str, pattern: str, variants: int = 1):
        self.module = module
        self.pattern = []
        self.rule = Nonterminal(rule)

        while pattern:
            match = self.regex.search(pattern)

            if match:
                nonterminal = match.group()
                terminal, pattern = map(lambda s: s.strip(), pattern.split(nonterminal, 1))

                if terminal:
                    self.pattern.append(Terminal(terminal))
                
                self.pattern.append(Nonterminal(nonterminal))

            else:
                pattern = pattern.strip()
                if pattern:
                    self.pattern.append(Terminal(pattern))
                    pattern = None

        Grammar.K = max(Grammar.K, len(self.pattern))

        if not (
            (len(self.pattern) == 1) 
            and (variants == 1)
        ): self.optimize()


    def optimize(self) -> None:
        """Pattern optimization by substituting terminals with single-alternative nonterminals."""

        for i, token in enumerate(self.pattern):
            if (
                isinstance(token, Terminal) 
                and (not token.name in Grammar.TERMINALS.values())
            ):
                new_rule, regex = Nonterminal(token.sub()), token.name
                self.pattern[i] = new_rule
                
                Grammar.add_terminal(new_rule, regex)
                self.module.rules.add(Production(self.module, new_rule.name, regex))


    def _str(self) -> str:
        return " ".join(str(token) for token in self.pattern)
    

    def compile(self) -> str:
        return self._str()


    def embed(self) -> str:
        return "[" + ", ".join(token.embed() for token in self.pattern) + "]"
    


class Nonterminal:
    def __init__(self, nonterminal: str):
        self.name = nonterminal.strip().upper().removeprefix("<").removesuffix(">")
        

    def __repr__(self):
        return f"<{self.name}>"
    

    def __len__(self) -> int:
        return len(self.name)
    

    def embed(self) -> str:
        return self.name



class Terminal:
    def __init__(self, name: str):
        self.name = name


    def sub(self) -> int:
        return f"<T_{abs(hash(self.name)%100000)}>"


    def __str__(self):
        return self.name
    

    def __repr__(self):
        return f"T[{self}]"
    

    def embed(self) -> str:
        return f"r'{self.name}'"



if __name__ == "__main__":
    test = Grammar("languages/banter")
    print(test.compile())
