from datatypes import OrderedSet
from utils import (
    preprocess_text, 
    print_warning,
    get_config
)

import os
import re



class Grammar:
    TERMINALS = {}
    K = 0
    INDENT_SENSITIVE = False
    NEWLINE_SENSITIVE = False
    WARNINGS = {
        "dependency" : [],
        "main"       : []
    }
    

    def __init__(self):
        self.main = get_config("paths", "language")

        self.modules = {}
        self.dependencies = self.traverse_dependencies(self.main, main=True)

        for module, lines in self.modules.items():
            self.modules[module] = Module("MAIN" if module == self.main else module, lines)

        print_warning("syntax not found", self.WARNINGS)


    def traverse_dependencies(self, path: str, main: bool = False) -> OrderedSet:
        """Recursively search for `#require`s from a top-level path, preserving order and building grammar modules during traversal.
        Searches for syntax.txt files in base directory; falls back to specific implementation if not found."""

        syntax = f"{path}/syntax.txt"
        if not os.path.exists(syntax):
            syntax = f"{path}/{get_config("implementation")}/syntax.txt"

        dependencies = OrderedSet()

        if os.path.exists(syntax):

            with open(syntax) as file:
                lines = preprocess_text(file)
                
                basic_requirements = [
                    line.removeprefix("#require").strip().replace(".", "/")
                    for line in lines if line.startswith("#require")
                ]

                requirements = OrderedSet()

                while basic_requirements:
                    requirement = basic_requirements.pop(0)
                    if "/" in requirement:
                        requirements.extend(f".lib/{"/".join(requirement.split("/")[:i+1])}" for i in range(requirement.count("/")))

                    requirements.add(".lib/" + requirement)

                self.modules[path] = filter(lambda x: not x.startswith("#require"), lines)

                dependencies.extend(requirements)

                for requirement in requirements:
                    dependencies.extend(self.traverse_dependencies(requirement))

        else: self.WARNINGS["main" if main else "dependency"].append(path)

        return dependencies

    
    @staticmethod
    def add_terminal(rule: 'Nonterminal', regex: str) -> None:
        """Adds a new terminal to the `Grammar`, binding it to the provided regular expression."""
        Grammar.TERMINALS[rule] = regex


    def __str__(self) -> str:
        return "\n\n".join(module._str() for module in self.modules.values())
    

    def compile(self) -> str:
        text = f"""'''!!! THIS FILE IS AUTOMATICALLY GENERATED - PLEASE DO NOT MODIFY !!!'''

        

from datatypes import Rule
from utils import *



##### ABSTRACT SYNTAX TREE #####


        {"".join(module.compile() for module in self.modules.values())}

##### GRAMMAR #####



MODULES = {self.embed()}

GRAMMAR = {{}}

for module, subgrammar in MODULES.items():
    for rule, alternatives in subgrammar.items():
        if not rule in GRAMMAR: GRAMMAR[rule] = {{}}
        if not module in GRAMMAR[rule]: GRAMMAR[rule][module] = []

        GRAMMAR[rule][module] += alternatives

        
                
##### ADDENDA #####



TERMINALS = {{
    rule : (module, re.compile(alternatives[0][0]))
            for rule, modules in GRAMMAR.items()
        for module, alternatives in modules.items() if (
    1 == len(alternatives) == len(alternatives[0])
    and isinstance(alternatives[0][0], str)
    )
}}

INDENT_SENSITIVE = {self.INDENT_SENSITIVE}

NEWLINE_SENSITIVE = {self.NEWLINE_SENSITIVE}

K = {Grammar.K}



##### HELPER FUNCTIONS #####



def expected_patterns(x) -> tuple[Rule, int, list]:
    return EXPECTED_PATTERNS.get(type(x), [])


def nullable(x): return type(x) in NULLS


def expects(previous: Rule|str, next: str|None) -> bool:
    '''Check if `previous` expects `next` or either are `None`.'''
    return (previous == None) or (next == None) or (type(next) in EXPECTED_TOKENS.get(type(previous), []))



##### GRAMMAR POSTPROCESSING / EXPANSION #####



NULLS             = find_nullable_rules(GRAMMAR)
GRAMMAR           = eliminate_nulls(GRAMMAR, NULLS)
EXPECTED_TOKENS   = build_expected_tokens(GRAMMAR)
EXPECTED_PATTERNS = build_expected_patterns(GRAMMAR)
"""
        
        return text
    
    
    def embed(self) -> str:
        return "{\n\n" + ",\n\n".join(module.embed() for module in self.modules.values()) + "\n\n}"



class Module:
    def __init__(self, name: str, lines: list, sep: str = "::="):
        self.name = "MAIN" if name == get_config("language") else name.removeprefix(".lib/").upper().replace("/", "_")
        self.lines = lines
        self.rules = OrderedSet()
        self.indent = 7

        for line in lines:
            self.add_rule(*line.split(sep))
            self.indent = max(self.indent, line.index(sep)-len(sep))


    def add_rule(self, rule: str, regex: str) -> None:
        self.rules.add(Production(self, rule, regex))


    def _str(self) -> str:
        return f"{self.name}\n" + "\n".join(production._str(self.indent) for production in self.rules)


    def compile(self) -> str:
        text = f"""
### MODULE : {self.name} ###

{"".join(production.compile() for production in self.rules)}
"""
        
        return text


    def embed(self) -> str:
        return f"'{self.name}' : {{\n" + (
            ",\n".join("   " + production.embed(self.indent) for production in self.rules) if self.rules 
            else "#  No rules found"
        ) + "\n   }"
    


class Production:
    sep = re.compile(r"[^\\]\|")

    
    def __init__(self, module: Module, rule: str, alternatives: str):
        self.module = module

        alternatives = self.sep.split(alternatives)
        variants = len(alternatives)
        
        self.rule, self.alternatives = Nonterminal(rule.strip()), [Pattern(module, rule, pattern, variants) for pattern in alternatives]


    def _str(self, indent: int) -> str:
        return f"{self.rule} {" " * (indent-len(self.rule))} ::= {f"\n{" " * (indent + 5)} | ".join(pattern._str() for pattern in self.alternatives)}"


    def compile(self) -> str:
        text = f"""
class {self.rule.name}(Rule):
   r'''```
{self.rule} ::= {f"\n{" " * (len(self.rule) + 5)}| ".join(pattern.compile() for pattern in self.alternatives)}
    ```'''
"""
        
        return text


    def embed(self, indent: int) -> str:
        return f"{self.rule.name} {" " * (indent-len(self.rule.name))} : [{f", ".join(pattern.embed() for pattern in self.alternatives)}]"



class Pattern:
    regex = re.compile(r"\<[A-Z0-9_]+\>")


    def __init__(self, module: Module, rule: str, pattern: str, variants: int = 1):
        self.module = module
        self.pattern = []
        self.rule = Nonterminal(rule)

        while pattern:
            match = self.regex.search(pattern)

            if match:
                nonterminal = match.group()
                terminal, pattern = map(lambda s: s.strip(), pattern.split(nonterminal, 1))

                if nonterminal in ("<INDENT>", "<DEDENT>") and not Grammar.INDENT_SENSITIVE:
                    Grammar.INDENT_SENSITIVE = True
                    self.module.add_rule("<INDENT>", get_config("special", "indent"))
                    self.module.add_rule("<DEDENT>", get_config("special", "dedent"))
                if terminal == r"\n":
                    Grammar.NEWLINE_SENSITIVE = True

                if terminal:
                    self.pattern.extend(Terminal(token) for token in terminal.split())
                
                self.pattern.append(Nonterminal(nonterminal))

            else:
                pattern = pattern.strip()
                if pattern:
                    self.pattern.extend(Terminal(token) for token in pattern.split())
                    pattern = None

        Grammar.K = max(Grammar.K, len(self.pattern))

        if not (
            (len(self.pattern) == 1) 
            and (variants == 1)
        ): self.optimize()


    def optimize(self) -> None:
        """Pattern optimization by substituting terminals with single-alternative nonterminals."""

        for i, token in enumerate(self.pattern):
            if isinstance(token, Terminal):
                if (token.regex in Grammar.TERMINALS.values()):
                    for new_rule, regex in Grammar.TERMINALS.items():
                        if (regex == token.regex):
                            self.pattern[i] = new_rule
                            break     
                else:
                    new_rule, regex = Nonterminal(token.asRule()), token.regex
                    self.pattern[i] = new_rule
                    
                    Grammar.add_terminal(new_rule, regex)
                    self.module.add_rule(new_rule.name, regex)
                    

    def _str(self) -> str:
        return " ".join(str(token) for token in self.pattern)
    

    def compile(self) -> str:
        return self._str()


    def embed(self) -> str:
        return "[" + ", ".join(token.embed() for token in self.pattern) + "]"
    


class Nonterminal:
    def __init__(self, nonterminal: str):
        self.name = nonterminal.strip().upper().removeprefix("<").removesuffix(">")
        

    def __repr__(self):
        return f"<{self.name}>"
    

    def __len__(self) -> int:
        return len(self.name)
    

    def embed(self) -> str:
        return self.name



class Terminal:
    def __init__(self, name: str):
        self.regex = name


    def asRule(self) -> str:
        """Constructs a unique nonterminal identifier for grammar optimization."""
        return f"<T_{str(hash(self.regex))[2:7]}>"


    def __str__(self):
        return self.regex
    

    def __repr__(self):
        return f"T[{self}]"
    

    def embed(self) -> str:
        return f"r'{self.regex}'"
