from datatypes import OrderedSet

import os
import re



class Grammar:
    TERMINALS = {}
    K = 0
    

    def __init__(self, path: str):
        self.path = path
        self.modules = {}
        self.dependencies = self.traverse_dependencies(self.path)


    def traverse_dependencies(self, path: str) -> OrderedSet:
        """Recursively search for `#require`s from a top-level path, preserving order and building grammar modules during traversal."""

        syntax = f"{path}/syntax.txt"
        dependencies = OrderedSet()

        if os.path.exists(syntax):

            with open(syntax) as file:
                lines = [ line for line in file.read().split("\n") if line ]
                
                basic_requirements = [
                    line.removeprefix("#require").strip().replace(".", "/")
                    for line in lines if line.startswith("#require")
                ]

                requirements = OrderedSet()

                while basic_requirements:
                    requirement = basic_requirements.pop(0)
                    if "/" in requirement:
                        requirements.extend(f".lib/{"/".join(requirement.split("/")[:i+1])}" for i in range(requirement.count("/")))

                    requirements.add(".lib/" + requirement)

                lines = filter(lambda x: not x.startswith("#require"), lines)
                self.modules[path] = Module(path, lines)

                dependencies.extend(requirements)

                for requirement in requirements:
                    dependencies.extend(self.traverse_dependencies(requirement))

        else: print(f"WARNING: syntax not found in dependency {path}")

        return dependencies

    
    @staticmethod
    def add_terminal(rule: 'Nonterminal', terminal: str) -> None:
        """Adds a new terminal to the `Grammar`."""
        Grammar.TERMINALS[rule] = terminal


    def __str__(self) -> str:
        return "\n\n".join(module._str() for module in self.modules.values())
    

    def compile(self) -> str:
        text = f"""'''!!! THIS FILE IS AUTOMATICALLY GENERATED - PLEASE DO NOT MODIFY !!!'''

        

from datatypes import Rule



##### ABSTRACT SYNTAX TREE #####


        {"".join(module.compile() for module in self.modules.values())}

##### GRAMMAR #####



GRAMMAR = {self.embed()}



##### ADDENDA #####



TERMINALS = {{
   {",\n   ".join(f"{rule.name} : r'{terminal}'" for rule, terminal in Grammar.TERMINALS.items())}
}}

K = {Grammar.K}

TOKENS = {{
    *TERMINALS,
    *GRAMMAR
}}

EXPECTED_TOKENS = {{
    token : [] for token in TOKENS
}}

EXPECTED_PATTERNS = {{
    token : [] for token in TOKENS
}}

EPSILON = "ε"

EPSILA: set = {{EPSILON}}

INDENT_SENSITIVE = False

NEWLINE_SENSITIVE = False

INDENT = "   "



##### HELPER FUNCTIONS #####



def retype(x): return type(x) if isinstance(x, Rule) else x


def expected_patterns(x) -> tuple[Rule, int, list]: return EXPECTED_PATTERNS[retype(x)]


def nullable(x): return retype(x) in EPSILA


def expects(previous: Rule|str, next: str|None) -> bool:
    '''Check if `previous` expects `next` or `previous` is `None`.'''
    return previous == None or next == " " or retype(next) in EXPECTED_TOKENS.get(retype(previous), [])


def expand_expected(token, x):
    not x in EXPECTED_TOKENS[token] and EXPECTED_TOKENS[token].append(x)

    for alternative in GRAMMAR.get(x, []):
        for y in alternative:
            if not y in EXPECTED_TOKENS[token]:
                expand_expected(token, y)
            if not y in EPSILA: break



##### GRAMMAR POSTPROCESSING / EXPANSION #####



# Collect nullable rules (i.e. rules that can be expanded from EPSILON)
count = 0
while count < len(EPSILA):
    for rule, alternatives in GRAMMAR.items():
        for pattern in alternatives:
            if (
                len(pattern) == 1
                and pattern[0] in EPSILA
                and rule not in EPSILA
            ):
                EPSILA.add(rule)
    count += 1
del count


# Grammar post-processing/expansion
for rule, alternatives in GRAMMAR.items():
    GRAMMAR[rule] = []

    for variant, pattern in enumerate(alternatives):
        # Expand nullable patterns
        expanded_null_patterns = [[]]
        for i, token in enumerate(pattern):
            if not token == EPSILON:
                expanded_null_patterns = list(state + [token] for state in expanded_null_patterns)
                if nullable(token):
                    expanded_null_patterns += list(state[:-1] for state in expanded_null_patterns)

        for expanded_null_pattern in expanded_null_patterns:
            if expanded_null_pattern and not (
                expanded_null_pattern in GRAMMAR[rule]
                or len(expanded_null_pattern) == 1 and expanded_null_pattern[0] == rule
            ):
                GRAMMAR[rule].append([variant] + expanded_null_pattern)

# Only construct expected tokens/patterns with the full expansion of the grammar
for rule, alternatives in GRAMMAR.items():                
    for pattern in alternatives:
        variant = pattern.pop(0)

        # Expand expected patterns 
        for token in pattern:
            if not (rule, variant, pattern) in EXPECTED_PATTERNS[token]: 
                EXPECTED_PATTERNS[token].append((rule, variant, pattern))

for rule, alternatives in GRAMMAR.items():                
    for pattern in alternatives:
    
        # Expand expected tokens
        for i, token in enumerate(pattern[:-1]):
            expand_expected(token, pattern[i+1])
"""
        
        return text
    
    
    def embed(self) -> str:
        return "{\n\n" + ",\n\n".join(module.embed() for module in self.modules.values()) + "\n\n}"



class Module:
    def __init__(self, name: str, lines: list, sep: str = "::="):
        self.name = name
        self.lines = lines
        self.rules = OrderedSet()

        self.indent = 0

        for line in lines:
            self.rules.add(Production(self, *line.split(sep)))
            self.indent = max(self.indent, line.index(sep)-len(sep))


    def _str(self) -> str:
        return f"{self.name}\n" + "\n".join(production._str(self.indent) for production in self.rules)


    def compile(self) -> str:
        text = f"""
### DEPENDENCY : {self.name} ###

{"".join(production.compile() for production in self.rules)}
"""
        
        return text


    def embed(self) -> str:
        return f"#  {self.name}\n" + (
            ",\n".join("   " + production.embed(self.indent) for production in self.rules) if self.rules 
            else "#  No rules found"
        )
    


class Production:
    sep = re.compile(r"[^\\]\|")

    
    def __init__(self, module: Module, rule: str, alternatives: str):
        self.module = module
        self.rule, self.alternatives = Nonterminal(rule.strip()), [Pattern(module, rule, pattern) for pattern in self.sep.split(alternatives)]


    def _str(self, indent: int) -> str:
        return f"{self.rule} {" " * (indent-len(self.rule))} ::= {f"\n{" " * (indent + 5)} | ".join(pattern._str() for pattern in self.alternatives)}"


    def compile(self) -> str:
        text = f"""
class {self.rule.name}(Rule):
   r'''```
{self.rule} ::= {f"\n{" " * (len(self.rule) + 5)}| ".join(pattern.compile() for pattern in self.alternatives)}
    ```'''
"""
        
        return text


    def embed(self, indent: int) -> str:
        return f"{self.rule.name} {" " * (indent-len(self.rule))} : [{f", ".join(pattern.embed() for pattern in self.alternatives)}]"



class Pattern:
    nonterminal = re.compile(r"\<[A-Z0-9_]+\>")


    def __init__(self, module: Module, rule: str, pattern: str):
        nonterminals = self.nonterminal.findall(pattern.strip())
        self.module = module
        self.pattern = []
        self.rule = Nonterminal(rule)

        # Divide pattern by matching nonterminals
        for nonterminal in nonterminals:
            while not pattern.startswith(nonterminal):
                terminal, pattern = pattern.split(" ", 1)
                if terminal: self.pattern.append(Terminal(terminal))

            self.pattern.append(Nonterminal(nonterminal))
            pattern = pattern.removeprefix(nonterminal)

        # Handle any remaining terminals
        self.pattern.extend(Terminal(terminal) for terminal in pattern.split(" ") if terminal)

        Grammar.K = max(Grammar.K, len(self.pattern))

        self.optimize()


    def optimize(self) -> None:
        """Pattern optimization by substituting terminals with single-alternative nonterminals."""

        if len(self.pattern) > 1:
            for i, token in enumerate(self.pattern):
                if isinstance(token, Terminal):
                    new_rule, pattern = Nonterminal(token.sub()), token.name
                    self.pattern[i] = new_rule
                    if not (pattern in Grammar.TERMINALS):
                        # Grammar.add_terminal(rule, pattern)
                        self.module.rules.add(Production(self.module, new_rule.name, pattern))
        else:
            token = self.pattern[0]
            if isinstance(token, Terminal):
                Grammar.add_terminal(self.rule, token.name)


    def _str(self) -> str:
        return " ".join(str(token) for token in self.pattern)
    

    def compile(self) -> str:
        return self._str()


    def embed(self) -> str:
        return "[" + ", ".join(token.embed() for token in self.pattern) + "]"
    


class Nonterminal:
    def __init__(self, nonterminal: str):
        self.name = nonterminal.strip().upper().removeprefix("<").removesuffix(">")
        

    def __repr__(self):
        return f"<{self.name}>"
    

    def __len__(self) -> int:
        return len(self.name)
    

    def embed(self) -> str:
        return self.name



class Terminal:
    def __init__(self, name: str):
        self.name = name


    def sub(self) -> int:
        return f"<T_{abs(hash(self.name)%100000)}>"


    def __str__(self):
        return self.name
    

    def __repr__(self):
        return f"T[{self}]"
    

    def embed(self) -> str:
        return f"r'{self.name}'"



if __name__ == "__main__":
    test = Grammar("languages/banter")
    # print(test)
    print(test.compile())
