from utils import *
from datatypes import OrderedSet, Nonterminal

from os.path import exists



REQUIREMENTS = OrderedSet()
DEFAULTS = {
    "alt" : "|",
    "lbrace" : "<",
    "rbrace" : ">",
    "production" : "::="
}



def compile_language(path: str) -> None:

    print(f"Compiling: {path.rsplit("/")[-1]}")
    print()

    # Have to compute before compiling semantics since that uses REQUIREMENTS.
    RULES: list = build_grammar(path)

    print()
    
    # The main parent path is not considered a requirement.
    REQUIREMENTS.pop(path)

    with open("eval.py", "w") as file:
        semantics_text = generate_eval(path)
        file.write(semantics_text)

    with open("AST.py", "w") as file:
        # First computes addenda (attributes from semantics),
        # then completes the syntax processing into a full `dict`,
        # then uses that `dict` to generate the AST file.
        file.write(generate_AST(path, process_syntax(RULES)))

    print()
    print("Done!")



def generate_eval(main_path: str) -> str:
    """Generates the text for `eval.py` from any semantic files attached to the `REQUIREMENTS` paths.
    
A note on semantic conventions:
    AST-bound operations should be prefixed with 'p_'
    Global functions and variables (e.g. the environment) with 'g_'
    """

    eval_text = f"""'''!!! THIS FILE IS AUTOMATICALLY GENERATED - PLEASE DO NOT MODIFY !!!'''

    

from datatypes import Rule, Parsed
from parser import parse
"""
    
    
    for folder in REQUIREMENTS:
        path = f"{folder}/semantics.py"
        if not exists(path): print(f"WARNING: semantics not found in dependency {folder}.")
        else:
            with open(path) as file:
                eval_text += f"""


##### DEPENDENCY: {folder} #####



""" + file.read()
                    

    semantics = main_path + "/semantics.py"
    if not exists(semantics): print(f"WARNING: semantics not found in main {main_path}.")
    else:
        with open(semantics) as file:
            eval_text += f"""


##### MAIN: {main_path} #####



""" + file.read()


    eval_text += f"""

    

##### EVAL #####



def null(x): return x(0) if isinstance(x, type(null)) else None


def lazy(expr: list): return lambda i: evaluate(expr[i])


def get_function(AST: Rule):
    return (
        globals().get(f"{{AST.fname}}_{{AST.variant}}")
        or globals().get(AST.fname)
        or null
    )


def evaluate(AST: Rule):
    return (
        get_function(AST)(lazy(AST.children)) if isinstance(AST, Rule)
        else AST
    )


def process(string: str, dFlag: bool) -> any:
    try:
        out = evaluate(parse(string, dFlag=dFlag).AST)
        if out: print(out)
    except Exception as e:
        if (
            len(e.args) > 1
            and e.args[0] in (0, 1)
        ):
            print(e.args[1])
        else:
            raise e
        

def validate(parsed: Parsed, solution: any) -> str:
    if str(parsed) == solution: return solution
    
    result = evaluate(parsed.AST)
    
    if result == solution: return solution
    raise ValueError(f"value of {{parsed}} should be {{solution}}, but received {{result}}")
"""


    return eval_text



def read_attributes(eval_text: str) -> dict[Nonterminal, list]:
    """Build a dictionary of modified grammar rules from semantics file text."""
    
    lines = eval_text.splitlines()
    addenda: dict[Nonterminal, list] = {}

    for line in lines:
        if line.startswith("#!"):
            # e.g.
            #! <if_then> ::= if <comparison>, then NEWLINE <block>
            rule, alternatives = line.removeprefix("#!").strip().split("::=")
            addenda[Nonterminal(rule)] = [split_pattern(pattern) for pattern in alternatives.split("|")]
    
    return addenda



def generate_AST(path: str, GRAMMAR: dict) -> None:
    """
Generates an AST from a context-free grammar.
    
:param str path: Path to a folder containing at least a `syntax.txt` file.
    """
    
    print()
    offset = show_grammar(GRAMMAR)

    TERMINALS = OrderedSet(
        token
                for alternatives in GRAMMAR.values()
            for pattern in alternatives
        for token in pattern if is_terminal(token)
        )

    AST_text = f"""'''!!! THIS FILE IS AUTOMATICALLY GENERATED - PLEASE DO NOT MODIFY !!!'''      



from datatypes import Rule, StrictRule
LANGUAGE = '{path}'



##### ABSTRACT SYNTAX TREE #####


"""

    for (rule, alternatives) in GRAMMAR.items():
        
        docstring = f"\n{" "*(len(rule)+5)}| ".join(" ".join(pattern) for pattern in alternatives)
        AST_text += f"""
class {rule}({rule.type}): 
    '''```
<{rule}> ::= {docstring}
    ```'''
"""

    AST_text += f"""

        
##### GRAMMAR #####


    
GRAMMAR = {{
    {",\n    ".join(f'''{rule}{" " * (offset - len(rule))} : [{
        ",".join(f"[{", ".join(s[1:-1] if is_nonterminal(s) else f"'{s}'" for s in alternative)}]"
                for alternative in alternatives)}]'''
                    for rule, alternatives in GRAMMAR.items())}
}}



##### USEFUL VARIABLES #####



FIRST = {list(GRAMMAR)[0]}

K = {max(map(len, (pattern for alternatives in GRAMMAR.values() for pattern in alternatives)))}

EPSILON = "ε"

TERMINALS = {{
   {",\n   ".join((f"'{t}'" for t in sorted(TERMINALS, key=len, reverse=True)))}
}}.union({{" "}})

TOKENS = TERMINALS.union(GRAMMAR.keys())

EXPECTED_TOKENS = {{ token : [] for token in TOKENS }}

EXPECTED_PATTERNS = {{ token : [] for token in TOKENS }}

EPSILA: set = {{EPSILON}}

{"\n\n".join(f"{modifier} = {val}" for modifier, val in Nonterminal.modifiers.items())}

INDENT = "   "

IGNORED = {{ " ", "\\n" }}



##### HELPER FUNCTIONS #####



def retype(x): return type(x) if isinstance(x, Rule) else x


def expected_patterns(x) -> tuple[Rule, int, list]: return EXPECTED_PATTERNS[retype(x)]


def nullable(x): return retype(x) in EPSILA


def expects(previous: Rule|str, next: str|None) -> bool:
    '''Check if `previous` expects `next` or `previous` is `None`.'''
    return previous == None or next == " " or retype(next) in EXPECTED_TOKENS.get(retype(previous), [])


def expand_expected(token, x):
    not x in EXPECTED_TOKENS[token] and EXPECTED_TOKENS[token].append(x)

    for alternative in GRAMMAR.get(x, []):
        for y in alternative:
            if not y in EXPECTED_TOKENS[token]:
                expand_expected(token, y)
            if not y in EPSILA: break



##### GRAMMAR POSTPROCESSING / EXPANSION #####



# Collect nullable rules (i.e. rules that can be expanded from EPSILON)
count = 0
while count < len(EPSILA):
    for rule, alternatives in GRAMMAR.items():
        for pattern in alternatives:
            if (
                len(pattern) == 1
                and pattern[0] in EPSILA
                and rule not in EPSILA
            ):
                EPSILA.add(rule)
    count += 1
del count


# Grammar post-processing/expansion
for rule, alternatives in GRAMMAR.items():
    GRAMMAR[rule] = []
    
    for variant, pattern in enumerate(alternatives):

        # Expand nullable patterns
        expanded_null_patterns = [[]]
        for i, token in enumerate(pattern):
            if not token == EPSILON:
                expanded_null_patterns = list(state + [token] for state in expanded_null_patterns)
                if nullable(token):
                    expanded_null_patterns += list(state[:-1] for state in expanded_null_patterns)

        for expanded_null_pattern in expanded_null_patterns:
            if expanded_null_pattern and not (
                expanded_null_pattern in GRAMMAR[rule]
                or len(expanded_null_pattern) == 1 and expanded_null_pattern[0] == rule
            ):
                GRAMMAR[rule].append([variant] + expanded_null_pattern)

# Only construct expected tokens/patterns with the full expansion of the grammar
for rule, alternatives in GRAMMAR.items():                
    for pattern in alternatives:
        variant = pattern.pop(0)

        # Expand expected patterns 
        for token in pattern:
            if not (rule, variant, pattern) in EXPECTED_PATTERNS[token]: 
                EXPECTED_PATTERNS[token].append((rule, variant, pattern))

for rule, alternatives in GRAMMAR.items():                
    for pattern in alternatives:
    
        # Expand expected tokens
        for i, token in enumerate(pattern[:-1]):
            expand_expected(token, pattern[i+1])
"""
    
    return AST_text



def build_grammar(path: str) -> list[tuple[Nonterminal, list]]:
    """
Recursively build a complete list of grammar rules from path.
Constructs `REQUIREMENTS` from path search.

:param str path: Path to a directory containing at least a `syntax.txt` file, and any dependencies.

:return: Returns the rules as a list of tuples .
    """

    rules = []
    dependency_rules = []
    symbols = DEFAULTS.copy()

    if not path in REQUIREMENTS:
        REQUIREMENTS.add(path)
        syntax_file = f"{path}/syntax.txt"

        if exists(syntax_file):
            with open(syntax_file) as file:
                syntax = preprocess_text(file)

                for line in syntax:

                    # Change alternation symbol
                    if line.startswith("#set"):
                        _, option, symbol = line.split()

                        symbols[option] = DEFAULTS[option] if symbol == "default" else symbol

                    # Expand #require lines into the grammars of their modules
                    elif line.startswith("#require"):
                        # Enumerate direct dependencies (i.e. dependencies specified in the #require line) 
                        dependencies = (dependency.removesuffix(",").strip() for dependency in line.split()[1:] if dependency.strip())
                        
                        # General dependency list will be expanded to include all indirect dependencies (i.e. math from math.infix)
                        for dependency in dependencies:
                            dependency = dependency.split(".")
                            for i, _ in enumerate(dependency):
                                dependency_rules = build_grammar(f"{LIB_PATH}/{'/'.join(dependency[:i+1])}") + dependency_rules
                    
                    # Process rules in top-level file            
                    else:
                        rule, alternatives = line.split(symbols["production"])
                        rule = Nonterminal(rule)
                        rules.append((
                            rule, 
                            [split_pattern(pattern, symbols["lbrace"], symbols["rbrace"]) for pattern in alternatives.split(symbols["alt"])]
                        ))
        
        else: print(f"WARNING: syntax not found in dependency {path}")
                        
    return rules + dependency_rules



def process_syntax(rules_list: list) -> dict[Nonterminal, list]:
    """Convert a list of `(rule, alternatives)` pairs into a fully processed dictionary of `{ rule : [*patterns] }`."""
    
    from main import dFlag
    
    grammar =  {}

    if dFlag: print(rules_list)

    for rule, alternatives in rules_list:

        # Prep rule entry; if rule already exists, continue to add alternatives
        grammar[rule] = grammar.get(rule, [])

        for pattern in alternatives:
            grammar[rule].append(pattern)

            # Replace terminals with nonterminals which exclusively produce them;
            # optimization for grouping sequences of characters. 
            if len(pattern) > 1:
                for i, token in enumerate(pattern):
                    if not (token.startswith("<") and token.endswith(">")):
                        new_rule = f"<T_{str(ordinal(token))}>"
                        pattern[i] = new_rule
                        if not new_rule in grammar:
                            grammar[Nonterminal(new_rule)] = [[token]]

    print()
    for dependency in sorted(REQUIREMENTS): print(dependency)
    
    if dFlag:
        print()
        print(grammar)
    
    return grammar
