#!/bin/bash


clear

# update TOC in README.md; now done through VScode extension Markdown All in One

# md_toc --in-place --no-list-coherence github -l3 ../README.md

# compile language

python3 main.py compile $1 $3

pyinstaller main.py \
    --onefile \
    --name=$2 \
    --add-data "config.json:."

rm -r build
rm ./*.spec
