#!/bin/bash

clear
python3 main.py -c $1
python3 -m nuitka --remove-output --python-flag="no_docstrings" --include-data-files=config.json=config.json --mode=onefile --output-filename=$2 main.py
python3 main.py -x $1
