#!/bin/bash


clear

# update TOC in README.md

python3 -m md_toc --in-place --no-list-coherence github -l6 ../README.md

# compile language

python3 main.py compile $1 $3

pyinstaller main.py \
    --onefile \
    --name=$2 \
    --add-data "config.json:."

rm -r build
rm ./*.spec
